#!/usr/bin/env bash

if ! type apt-add-repository &> /dev/null; then
    >&2 echo "apt-add-repository: command not found, try to install package - software-properties-common first!"
    exit 1
fi

for para in "$@"
do
    if [[ "${para}" = "ppa:"* ]];then
        ppa="${para}"
        break
    fi
done

if [ -z "${ppa}" ];then
    >&2 echo "Error: need a repository as argument"
    exit 1
fi

APT_COMMAND="apt-get"
if type apt &> /dev/null; then
    APT_COMMAND="apt"
fi

if apt-add-repository "$@"; then
    repo="$(echo "${ppa}" | awk -F'ppa:' '{print $2}' | sed 's/\//-/g')"
    file="$(ls "/etc/apt/sources.list.d/${repo}"*.list)"
    $APT_COMMAND update -o Dir::Etc::sourcelist="$file" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
fi
